services:
  app:
    build: .
    container_name: proye-is

    ports:
      - "8080:8080"

    volumes:
      - ./db:/app/db

    environment:
      db_url: jdbc:sqlite:/app/db/dev.db

    restart: unless-stopped